apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv
spec:
  capacity:
    storage: 4Gi  # Adjust this to your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # For demonstration purposes only; don't use in production!
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi  # Adjust this to your needs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0.30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: to_do_list
          volumeMounts:
            - name: mysqldb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysqldb-data
          persistentVolumeClaim:
            claimName: mysqldb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysqldb