version: '3'
name: 'tugas-devops'

services:
  mysqldb:
      image: mysql:8.0.30
      container_name: todo-list-mysqldb
      ports:
       - "3306:3306"
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: to_do_list
      volumes:
        - mysqldb-data:/var/lib/mysql  # Mount a volume for MySQL data
  web-backend:
    build: .
    container_name: todo-list-backend
    ports:
      - "8000:8000"
    image: todo-list-backend
    depends_on:
      - mysqldb

volumes:
  mysqldb-data:  # Define a volume for MySQL data