apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0.30
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: to_do_list
          volumeMounts:
            - name: mysqldb-data
              mountPath: /var/lib/mysql
      volumes: # Add this section
        - name: mysqldb-data
          emptyDir: {} # This creates an empty directory which can be used as a volume
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  ports:
    - port: 3306
  selector:
    app: mysqldb
